name: Playwright Tests
on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile add nixpkgs#devenv

    - name: Start backend / frontend
      run: devenv up -d

    - name: Populate db with seeds
      run: devenv shell seed

    # When not on main, fetch screenshots and run tests
    - name: Fetch screenshots (not main)
      if: github.ref != 'refs/heads/main'
      run: |
        cd frontend
        ./fetch_asset.sh "$GITHUB_BASE_REF"
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Run Playwright tests
      if: github.ref != 'refs/heads/main'
      run: |
        cd frontend
        npx playwright test

    # When on main, update snapshots as the standard
    - name: Run Playwright tests (update snapshots)
      if: github.ref == 'refs/heads/main'
      run: |
        cd frontend
        npx playwright test --update-snapshots

    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: screenshots
        path: frontend/tests/__screenshots__/
        retention-days: 30
